"""Initial migration

Revision ID: 36560a9c1d66
Revises: 
Create Date: 2026-01-23 22:52:55.354334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36560a9c1d66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fused_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('snapshot_top', sa.String(), nullable=True),
    sa.Column('snapshot_side', sa.String(), nullable=True),
    sa.Column('top_center_x', sa.Float(), nullable=True),
    sa.Column('top_center_y', sa.Float(), nullable=True),
    sa.Column('side_center_x', sa.Float(), nullable=True),
    sa.Column('side_center_y', sa.Float(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fused_objects_id'), 'fused_objects', ['id'], unique=False)
    op.create_index(op.f('ix_fused_objects_track_id'), 'fused_objects', ['track_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fused_objects_track_id'), table_name='fused_objects')
    op.drop_index(op.f('ix_fused_objects_id'), table_name='fused_objects')
    op.drop_table('fused_objects')
    # ### end Alembic commands ###
