"""Add_session_id

Revision ID: 4226b88cbd64
Revises: a695db15ae22
Create Date: 2026-03-04 23:01:52.687811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4226b88cbd64'
down_revision = 'a695db15ae22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fused_objects', sa.Column('session_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_fused_objects_track_id'), table_name='fused_objects')
    op.create_index(op.f('ix_fused_objects_track_id'), 'fused_objects', ['track_id'], unique=False)
    op.create_index(op.f('ix_fused_objects_session_id'), 'fused_objects', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fused_objects_session_id'), table_name='fused_objects')
    op.drop_index(op.f('ix_fused_objects_track_id'), table_name='fused_objects')
    op.create_index(op.f('ix_fused_objects_track_id'), 'fused_objects', ['track_id'], unique=True)
    op.drop_column('fused_objects', 'session_id')
    # ### end Alembic commands ###
