"""Add ML raw features and farm settings

Revision ID: 76981151b806
Revises: 4226b88cbd64
Create Date: 2026-03-11 22:35:26.159270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76981151b806'
down_revision = '4226b88cbd64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chick_in_date', sa.Date(), nullable=True),
    sa.Column('manual_age_override', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_settings_id'), 'farm_settings', ['id'], unique=False)
    op.add_column('fused_objects', sa.Column('age_days', sa.Integer(), nullable=True))
    op.add_column('fused_objects', sa.Column('mask_area_px', sa.Float(), nullable=True))
    op.add_column('fused_objects', sa.Column('bbox_width_px', sa.Float(), nullable=True))
    op.add_column('fused_objects', sa.Column('bbox_height_px', sa.Float(), nullable=True))
    op.add_column('fused_objects', sa.Column('cm_per_pixel', sa.Float(), nullable=True))
    op.add_column('fused_objects', sa.Column('actual_weight_gram', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fused_objects', 'actual_weight_gram')
    op.drop_column('fused_objects', 'cm_per_pixel')
    op.drop_column('fused_objects', 'bbox_height_px')
    op.drop_column('fused_objects', 'bbox_width_px')
    op.drop_column('fused_objects', 'mask_area_px')
    op.drop_column('fused_objects', 'age_days')
    op.drop_index(op.f('ix_farm_settings_id'), table_name='farm_settings')
    op.drop_table('farm_settings')
    # ### end Alembic commands ###
