"""Add class name for training data

Revision ID: 7e80f8daa7c3
Revises: de5c9d756ede
Create Date: 2026-03-13 14:36:00.809898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e80f8daa7c3'
down_revision = 'de5c9d756ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fused_objects', sa.Column('class_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fused_objects', 'class_name')
    # ### end Alembic commands ###
