"""Add estimated_weight and is_fused

Revision ID: a695db15ae22
Revises: 78901c9d3e88
Create Date: 2026-02-28 22:13:21.541988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a695db15ae22'
down_revision = '78901c9d3e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fused_objects', sa.Column('estimated_weight', sa.Float(), nullable=True))
    op.add_column('fused_objects', sa.Column('is_fused', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fused_objects', 'is_fused')
    op.drop_column('fused_objects', 'estimated_weight')
    # ### end Alembic commands ###
