"""Add statistics table

Revision ID: d7f149a07ab9
Revises: 76981151b806
Create Date: 2026-03-12 15:42:05.678194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f149a07ab9'
down_revision = '76981151b806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=True),
    sa.Column('total_valid_chickens', sa.Integer(), nullable=True),
    sa.Column('daily_average_kg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_stats_date'), 'daily_stats', ['date'], unique=True)
    op.create_index(op.f('ix_daily_stats_id'), 'daily_stats', ['id'], unique=False)
    op.create_table('session_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('total_chickens_detected', sa.Integer(), nullable=True),
    sa.Column('valid_chickens_used', sa.Integer(), nullable=True),
    sa.Column('ai_average_weight_kg', sa.Float(), nullable=True),
    sa.Column('ai_std_dev_kg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_stats_id'), 'session_stats', ['id'], unique=False)
    op.create_index(op.f('ix_session_stats_session_id'), 'session_stats', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_stats_session_id'), table_name='session_stats')
    op.drop_index(op.f('ix_session_stats_id'), table_name='session_stats')
    op.drop_table('session_stats')
    op.drop_index(op.f('ix_daily_stats_id'), table_name='daily_stats')
    op.drop_index(op.f('ix_daily_stats_date'), table_name='daily_stats')
    op.drop_table('daily_stats')
    # ### end Alembic commands ###
